// Shared sitemap utilities — HTML table rendering for browsers
export function sitemapHtmlTable(options: {
  title: string;
  description: string;
  columns: string[];
  rows: { cells: string[] }[];
}) {
  const { title, description, columns, rows } = options;
  
  const thead = columns.map((c) => `<th>${c}</th>`).join("");
  const tbody = rows
    .map(
      (r) =>
        `<tr>${r.cells.map((c) => `<td>${c}</td>`).join("")}</tr>`
    )
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>XML Sitemap | VIP Luxury Car Rental Dubai</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0A0A0A; color: #E5E5E5; padding: 40px 20px; }
    .container { max-width: 1000px; margin: 0 auto; }
    .header { background: linear-gradient(135deg, #C8A951, #A8872F); color: #0A0A0A; padding: 30px 40px; border-radius: 12px 12px 0 0; }
    .header h1 { font-size: 24px; font-weight: 700; margin-bottom: 6px; }
    .header p { font-size: 14px; opacity: 0.85; }
    .card { background: #151515; border: 1px solid #2A2A2A; border-top: none; padding: 20px 30px 30px; border-radius: 0 0 12px 12px; overflow-x: auto; }
    .info { color: #999; font-size: 13px; padding: 15px 0 20px; }
    .info strong { color: #E5E5E5; }
    table { width: 100%; border-collapse: collapse; min-width: 600px; }
    th { text-align: left; padding: 12px 14px; font-size: 11px; font-weight: 600; color: #C8A951; text-transform: uppercase; letter-spacing: 0.05em; border-bottom: 2px solid #2A2A2A; white-space: nowrap; }
    td { padding: 10px 14px; font-size: 13px; border-bottom: 1px solid #222; vertical-align: middle; word-break: break-all; }
    tr:last-child td { border-bottom: none; }
    tr:hover td { background: rgba(200, 169, 81, 0.04); }
    .url-link { color: #7CB7FF; text-decoration: none; font-size: 13px; word-break: break-all; }
    .url-link:hover { text-decoration: underline; color: #9CCBFF; }
    .badge { display: inline-block; padding: 1px 8px; border-radius: 12px; font-size: 10px; font-weight: 600; }
    .badge-imgs { background: rgba(107, 189, 107, 0.15); color: #6BBD6B; }
    .badge-high { background: rgba(200, 169, 81, 0.15); color: #C8A951; }
    .badge-med { background: rgba(123, 183, 255, 0.15); color: #7CB7FF; }
    .badge-low { background: rgba(153, 153, 153, 0.15); color: #999; }
    .footer { text-align: center; padding: 30px; color: #666; font-size: 13px; }
    .footer a { color: #C8A951; text-decoration: none; }
    .footer a:hover { text-decoration: underline; }
    .count { color: #6BBD6B; font-weight: 600; }
    .priority { font-size: 12px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>XML Sitemap</h1>
      <p>${description}</p>
    </div>
    <div class="card">
      <p class="info">This <strong>XML Sitemap</strong> contains <strong class="count">${rows.length}</strong> URLs.</p>
      <table>
        <tr>${thead}</tr>
        ${tbody}
      </table>
    </div>
    <div class="footer">
      Generated by VIP Luxury Car Rental Dubai |
      <a href="https://vipluxurycarrental.com/">Home</a> |
      <a href="https://vipluxurycarrental.com/sitemap-index/">Sitemap Index</a> |
      <a href="https://vipluxurycarrental.com/sitemap/">HTML Sitemap</a>
    </div>
  </div>
</body>
</html>`;
}
